### PR TITLE
Adress review feedback, please test!

### PR DESCRIPTION
**Pull request by Apollon77**
* update deps
* optimize timeout handling
* optimize object checks and creations to prevent unneeded db requests
* setStateChanged is checking state value if changed
* small things

### CODE REVIEW

**Comment by Apollon77** [comment]
Ok, I rebase ... now we overlap with our work

**Comment by Apollon77** [comment]
Ok, in fact we overlap too much ... maybe check the changes in my PR and adjust what you still want and ignore the rest  :-)

**Comment by nobl** [comment]
yeah :)
Sorry for that :( Should have checked my dev-environment first

But I think I can still pull some stuff in from your changes :)

**Comment by Apollon77** [comment]
all fine ... have fun, simply close afterwards

**Comment by nobl** [comment]
done :)

**Pull request closed without merging**
